name: qr_code
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.2.5 <4.0.0'

dependencies: 
  cloud_firestore: ^4.14.0
  cupertino_icons: ^1.0.2
  firebase_auth: ^4.16.0
  firebase_core: ^2.24.2
  flutter_barcode_scanner: ^2.0.0
  gap: ^3.0.1
  get: 4.6.6
  google_fonts: 6.1.0
  open_file_plus: ^3.4.1
  path_provider: ^2.1.2
  pdf: ^3.10.7
  printing: ^5.11.1
  qr_flutter: ^4.1.0
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter:
  uses-material-design: true
  fonts:
    - family: poppins
      fonts:
        - asset: assets/fonts/poppins.ttf
          style: normal
